[build]
  command = "npm run build && npm run export"
  publish = "out"
<<<<<<< HEAD
  functions = "functions"  
=======
  functions = "functions"  

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
>>>>>>> mongodb
